### ISSUE TITLE
Would it be possible for you to share how to use a fine-tuned CHGnet model?

### ISSUE THREAD

**Issue by rvillarparajo** [advancesoftcorp/lammps#16]
Hi!

First of all I would like to thank you for your great work in the integration of lammps and chgnet. I am struggling however to use the produced fine-tuned models. The trainer creates a folder with 3 .pth.tar files and I am not sure what I need to do with them to use them in lammps.

I am aware that you have a thread in their Github where this is mentioned but I am still lost about which path to specify in the inp.lammps for the pair_coeffs. Should I specify the path to the .pth.tar file?

Thanks in advance for your attention!

**Comment by advancesoftcorp** [comment]
fine-tuned model has only one .pht.tar file. check your process of fine-tuning.
