### ISSUE TITLE
Move DFTD3 import

### ISSUE THREAD

**Issue by shyuep** [advancesoftcorp/lammps#6]
https://github.com/advancesoftcorp/lammps/blob/1ab512916a99e38b46d1d8a6660b0212da95592f/src/ML-M3GNET/matgl_driver.py#L11C18-L11C18

Thanks for implementing the matgl_driver. I would like to suggest that the DFTD3 import be moved to just after line 48 (`if dftd3`). This will allow one to use the driver without having to install DFTD3 (which is actually what most people would be using). DFTD3 requires OpenMP, which can be a pain to install in some systems.

**Comment by advancesoftcorp** [comment]
You are right, I will do it. Thanks.
