### ISSUE TITLE
run errros，No module named 'chgnet_driver'

### ISSUE THREAD

**Issue by ly934684881** [advancesoftcorp/lammps#7]
Dear developers,
Hi, how can i solve this error，
i compiled the program with the following commands:
conda create -n  py310-new python=3.10
source activate py310-new
pip install chgnet==0.2.0

make yes-basic yes-ML-CHGNET yes-python
make intel_cpu_intelmpi mode=shared

LAMMPS (2 Jun 2022)
  using 28 OpenMP thread(s) per MPI task
Reading data file ...
  orthogonal box = (0 0 0) to (5.1499664 5.1499664 5.1499664)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  12 atoms
  read_data CPU = 0.023 seconds
ModuleNotFoundError: No module named 'chgnet_driver'
ERROR: Cannot initialize python for pair_coeff of CHGNet. (../pair_chgnet.cpp:503)
Last command: pair_coeff    * *  MPtrj-efsm  Zr O
yhrun: error: cn5237: task 0: Exited with exit code 1

**Comment by ly934684881** [comment]
Looking forward to your reply, thank you ^_^

**Comment by advancesoftcorp** [comment]
@ly934684881 
Please put the file "chgnet_driver.py" at the current directory, or set the path of the file by pari_style as https://github.com/advancesoftcorp/lammps/blob/0400823394c81e242e83b0120585969d06903374/examples/CHGNET/inp.lammps#L17 .

**Comment by ly934684881** [comment]
> @ly934684881 Please put the file "chgnet_driver.py" at the current directory, or set the path of the file by pari_style as
> 
> https://github.com/advancesoftcorp/lammps/blob/0400823394c81e242e83b0120585969d06903374/examples/CHGNET/inp.lammps#L17
> 
> .

Thank you very much for your advice
