### ISSUE TITLE
GPU accelerating for CHGNET and M3GNET

### ISSUE THREAD

**Issue by qw19980430** [advancesoftcorp/lammps#8]
Hi Developer

Many thanks to your effort.

I have a quick question: if I would like to perform GPU accelerating for CHGNET,  1. I use "pair_style    chgnet/gpu" 2. I install GPU package of lammps.  Am I right?  or I can directly run the gpu accelerated simulation on a GPU without installing GPU package of lammps?

BTW I don't see" pair_style    m3gnet/gpu",  can m3gnet also be accelerated by GPU?

Thanks

**Comment by advancesoftcorp** [comment]
For CHGNet,
  1. you have to write "pair_style chgnet/gpu" into input file of LAMMPS.
  2. Install CHGNet with pytorch-gpu.
  no need to install GPU package of LAMMPS.

For M3GNet,
  1. Install MatGL with pytorch-gpu.
