### ISSUE TITLE
Cannot run MD for Pm Element with M3GNet

### ISSUE THREAD

**Issue by JiQi535** [advancesoftcorp/lammps#9]
Hi, I found that the **Pm** element is wrongly spelled as **Rm** for M3GNet and CHGNet pair.cpp files.
https://github.com/advancesoftcorp/lammps/blob/2787a26d4b40b8cb0ae54de017ba056b69f3016d/src/ML-M3GNET/pair_m3gnet.cpp#L667-L676

**Comment by advancesoftcorp** [comment]
Thank you. I will fix it for M3GNet/CHGNet/OC20.
